### ISSUE TITLE
deploying in liquidity editor is broken

### ISSUE THREAD

**Issue by martinpospech** [OCamlPro/liquidity#148]
`KT1GE2AZhazRxGsAjRVkQccHcB2pvANXQWd7` is used for all contract instances in initial storage regardless of what's in the textbox.

(tested on the zeronet version)

**Comment by mebsout** [comment]
Are you using `Contract.self` in the initializer ? I've made a recent patch which forbids this and other instructions. In fact the initializer code is executed before the contract is deployed in the context of the current head of the node. Also the hash of a contract indirectly depends on the content of its initial storage in Tezos so it cannot appear there.

If I'm misunderstanding what the issue is, please provide an example.

**Comment by martinpospech** [comment]
I'm using other contracts that exist on the blockchain. The network tab in browser devtools shows that the run_operation request is run with `KT1GE2AZhazRxGsAjRVkQccHcB2pvANXQWd7` instead of the address specified in the GUI.

**Comment by lefessan** [comment]
Yes:
https://github.com/OCamlPro/liquidity/blob/next/tools/liquidity/liquidData.ml#L74
