### ISSUE TITLE
Example from Liquidity reference doesn't work

### ISSUE THREAD

**Issue by victornek** [OCamlPro/liquidity#161]
Tried this example:

let v = 1000tz in
let (nat, rem_tez) = v / 1tz in

Got the following: 
Type error: get takes a tuple as first argument, got: (nat : tez) option

Also, how to multiple one tez with another, when it's needed? For example, in the following piece, multiplying two tez values is not allowed:

let first_tez = 10tz in
let one_and_a_half_tez = first_tez * 1.5tz (* Type error: 2 bad args for primitive "*": tez tez *)

**Comment by ddeclerck** [comment]
Hi,

The example is indeed erroneous. Division returns an option type, to account for division by zero errors.

Something like this should work :
`let v = 1000tz in
match v / 1tz with
| Some  (nat, rem_tez) -> (* do something with nat and rem_tez *)
| None -> fail "Division by zero"`

As for the tez * tez multiplication, this is a limitation from the underlying Michelson language.
If one of the amounts is a constant, as in your example, then just use a nat constant (p suffix).
Otherwise, if really needed, you may just use a division to "cast" one of the tez amount to a nat :
`let first_tez = 10tz in
let second_tez = 1.5tz in
let second_tez_as_nat = match second_tez / 1tz with None -> fail "" | Some  (n, _) -> n in
let one_and_a_half_tez = first_tez * second_tez_as_nat`

**Comment by victornek** [comment]
Thanks. Still struggling trying to obtain 0.2867 from 20tz / 70tz. All I want is to get the ratio, but the option returns 0p as a nat part, 20tz as tez reminder.

**Comment by ddeclerck** [comment]
The language only offers an euclidian (integer) division (and as a matter of fact, there are no floating point numbers in Liquidity, because they are not available in Michelson either).

A possible solution for you would be to reason in thousandth, by multiplying by 1000p before dividing :
```ocaml
  let t1 = 20tz in
  let t2 = 70tz in
  let res = match t1 * 1000p / t2 with None -> failwith "" | Some  (n, _) -> n in
```
Which gives you res = 285p (you might also want to take into account the remainder of the division for proper rounding).
