### ISSUE TITLE
Difference between address and key_hash

### ISSUE THREAD

**Issue by dakk** [OCamlPro/liquidity#211]
During my experiments with liquidity, I fall into a misunderstanding: which is the difference between an address and a key_hash? And why I can't use an address con Account.transfer?

**Comment by mebsout** [comment]
An address is the handle of either a contract `KT1...` or an implicit account `tz1...` while a `key_hash` is the hash of a cryptographic public `key` which happens to also be a `tz1...` (or `tz2...`, `tz3...`).
You can go from `address` to smart contract, with `Contract.at` but this can fail if no contract (or a contract of the wrong type) is present at this address, so this is why this function returns an `option`.
You can go from `key_hash` to `address` with `Account.default`, this gives you the default implicit account associated with the tz1 (you cannot go the other way around, this is due to restrictions/missing opcodes in Michelson).
Using `key_hash`es to send tokens to an account is the safest way to do it, because this way you know that the transfer cannot fail (if you have enough funds), and this is what `Account.transfer` gives you. If you want to send tokens to an `address` then you have to transform it to a contract (with `Contract.at` or one of its variants) and then use `Contract.call`, but this is dangerous because there is no way to know (unless you statically know the destination) that the smart contract that you call will not execute code, and potentially fail.

**Comment by dakk** [comment]
Thank you @mebsout , your explanation was very clear.

I close the issue
