### ISSUE TITLE
Comparator overload for Map

### ISSUE THREAD

**Issue by fateyan** [OCamlPro/liquidity#222]
Hi, does Liquidity supports Comparator overload for Map?

As I knows, OCaml supports, but when I used the OCaml way to do it, the compiler throw out Syntax Error.

I want to do comparison on (bytes * address) type, I think both of them are comparable.

**Comment by mebsout** [comment]
Composed types are not comparable at the moment due to restrictions in Dune/Tezos, but this will probably change in a coming protocol update. This will be reflected in Liquidity at the same time.
In the meantime, a workaround is to use `Bytes.pack` and `Bytes.unpack` to convert elements to and from bytes, which is a comparable type.
