### ISSUE TITLE
record fields with identical names

### ISSUE THREAD

**Issue by something3** [OCamlPro/liquidity#76]
Right now records can't have fields with identical names.
This makes record types ugly.

Here's how it looks:
```
type foo = {
  baz : key;
}

type bar = {
  baz2 : key;
}
```
Is this by design and/or is there a better way to do this?

**Comment by mebsout** [comment]
Yes, this is by design. This restriction is inherited from OCaml itself. That is because there is no good way to infer the type of `x` in `x.baz`. This restriction could actually be lifted in some cases because type inference is currently quite minimal in Liquidity, but we would like to keep compatibility with OCaml as much as possible (and we might add more type inference in the future). One way to work around the issue is to use scoping (with modules in OCaml) which we don't have for the moment, so you have to use unique field names (within a single contract) which, I agree, is somewhat ugly.
