### ISSUE TITLE
Tezos with liquidtity 

### ISSUE THREAD

**Issue by sixfacearu** [OCamlPro/liquidity#79]
1-I have some program but I need explanation for how to write methods and how to return different data types then explain how to pass different number of (or) different types of arguments in parameters .
2-how I use tokens in tezos 
3-we need step by step tutorial for create testnetwork and how to deploy the contracts

**Comment by mebsout** [comment]
1. There are a bunch of examples you can look at in [tests/](https://github.com/OCamlPro/liquidity/tree/next/tests). Due to changes in Michelson, contracts do not return any value anymore but only modify the storage. If you want multiple arguments to a contract, you can put them in a tuple `(x, y, z)` type or a record. See [tests/others/morpion.liq](https://github.com/OCamlPro/liquidity/blob/next/tests/others/morpion.liq) for instance.
2. Tokens are passed when calling `transfer` in the tezos client. The value of the current transaction can be accessed with `Current.amount ()` in Liquidity.
3. You can use any zeronet node, for instance on http://www.liquidity-lang.org/zeronet/ and deploy and call contracts with the interface.
