### ISSUE TITLE
Michelson_v1_printer.unparse

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#84]
@ version 0.3

[contracts.zip](https://github.com/OCamlPro/liquidity/files/2169513/contracts.zip)

**Comment by mebsout** [comment]
I'm not sure what the issue is here.

But your example seems to be missaligned, this is due to a bug in the Tezos michelson pretty-printer. If you use the `liquidity-mini` version it should be ok as we use our own printer.

Also you are using `bytes` as keys of your map which I have now forbidden in liquidity because Tezos does not support it at the moment.

**Comment by catsigma** [comment]
I'm always use the mini version

**Comment by mebsout** [comment]
I was able to deploy `pool_token.liq` to the zeronet with try-liquidity by replacing type `bytes` with `string` (and occurences of `Bytes.pack` with `""`), see http://zeronet.tzscan.io/KT19GSqFMiaWU7oF4Em4zzRy7RGnCyWh9D2t. Maybe its an issue with the tezos client?
