### ISSUE TITLE
inline not working in 0.35

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#97]
with or without `[@@inline]` generate the same michelson result.

**Comment by mebsout** [comment]
`[@@inline]` is to force inlining (for functions in closures or functions with multiple calls for instance). If Liquidity detects that it can safely inline the function, it will do so even without the attribute.

**Comment by lefessan** [comment]
@mebsout Could you give an example ? Is there a test in `tests/` ?

**Comment by mebsout** [comment]
I have added a test in [test_inlining.liq](https://github.com/OCamlPro/liquidity/blob/next/tests/test_inline.liq), which shows when a function/variable is inlined or not.

**Comment by catsigma** [comment]
```
(* Will be inlined *)

let f (x:int) = x + 1



(* Won't be inlined *)

let g (x:int) = x + 2
```

what is the difference between `f` and `g`?

**Comment by mebsout** [comment]
`f` is used only once in the following code while `g` is used twice. `h` is also used twice but the `[@@inline]` attribute forces it to be inlined anyway. `op` is used twice but creates a value which is context dependant, _i.e._ two calls to `Contract.call` will not produce the same operation value, so the `[@@inline]` attribute is ignored for this variable because inlining is not safe in this case.

**Comment by catsigma** [comment]
Thanks.
